### ISSUE TITLE
how to use confluence_nms/confluence with yolo

### ISSUE THREAD

**Issue by rbchen1996** [ashep29/confluence#1]
I used your code in the Yolo algorithm and found that the performance is particularly poor. The performance of the confluence algorithm you proposed is far lower than that of the NMS algorithm. Can you help me explain this doubt

**Comment by ashep29** [comment]
Are you using confluence-nms or confluence? Confluence-nms is more suited to yolo due to the way proposals are generated. Confluence works best on sliding window based models like retinanet and faster rcnn.

Can you tell me what threshold are you using?

**Comment by rbchen1996** [comment]
Dear Author:&nbsp; &nbsp; &nbsp; &nbsp; I am so glad to hear from your letter.the yolov3 code I downloaded from&nbsp;https://github.com/ultralytics/yolov3,I replace the&nbsp;i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS&nbsp;code to&nbsp;from&nbsp;confluence import c_nms i = c_nms(boxes,scores,c),











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ashep29/confluence"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月24日(星期五) 晚上7:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ashep29/confluence] The actual effect of the algorithm is very poor (#1)





 
Are you using confluence-nms or confluence? Confluence-nms is more suited to yolo due to the way proposals are generated. Confluence works best on sliding window based models like retinanet and faster rcnn.
 
Can you tell me what threshold are you using?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ashep29** [comment]
Please ensure that you include the class labels too. This allows confluence to deal with multi-class object detection, i.e. confluence_nms(bounding_boxes,scores,**classes**,confluence_thr,gaussian,score_thr=0.05,sigma=0.5). Also, what is the value of "c" in this line i = c_nms(boxes,scores,c)?

The best way to use confluence and confluence_nms is to switch off nms in your original code. If you do, you should see many boxes around each object. Next, add in confluence or confluence_nms, and vary the confluence threshold (confluence_thr) between 0 and 2. You should get the best results between 0.5 and 0.8

**Comment by rbchen1996** [comment]
the value of "c" I have drawn in the picture,it is the class labels. I also set confluence_thr between 0.5 and 0.8,but the result&nbsp;are similar to NMS






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ashep29/confluence"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月29日(星期三) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ashep29/confluence] The actual effect of the algorithm is very poor (#1)





 
Please ensure that you include the class labels too. This allows confluence to deal with multi-class object detection, i.e. confluence_nms(bounding_boxes,scores,classes,confluence_thr,gaussian,score_thr=0.05,sigma=0.5). Also, what is the value of "c" in this line i = c_nms(boxes,scores,c)?
 
The best way to use confluence and confluence_nms is to switch off nms in your original code. If you do, you should see many boxes around each object. Next, add in confluence or confluence_nms, and vary the confluence threshold (confluence_thr) between 0 and 2. You should get the best results between 0.5 and 0.8
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ashep29** [comment]
C-NMS will generate similar results to NMS in sparse settings where there isn't much occlusion, however in densely packed images you should see noticeable improvement.
