### ISSUE TITLE
关于多目标检测

### ISSUE THREAD

**Issue by Adong-1209** [ashep29/confluence#2]
请问您的这个confluence代码支持多目标检测吗

**Comment by ashep29** [comment]
Yes

**Comment by Adong-1209** [comment]
If obj_conf is included in the prediction result, how can I use conference

**Comment by ashep29** [comment]
I'm not sure what you mean? If you switch NMS off, you can then pass the bounding boxes, confidence scores and class labels into confluence as is.

**Comment by Adong-1209** [comment]
Thanks,I get it
